window.PLANETENUHR_PHENOMENA = {
  meteorStreams: [
    { key: "quadrantids", name: "Quadrantids", start: "12-28", end: "01-12", peak: "01-03", radiant: "Bootes", radiantAngle: 35, radiantAltitude: 56, color: "#2563eb" },
    { key: "lyrids", name: "Lyrids", start: "04-16", end: "04-25", peak: "04-22", radiant: "Lyra", radiantAngle: 68, radiantAltitude: 62, color: "#7c3aed" },
    { key: "eta_aquariids", name: "Eta Aquariids", start: "04-19", end: "05-28", peak: "05-06", radiant: "Aquarius", radiantAngle: 125, radiantAltitude: 28, color: "#0891b2" },
    { key: "delta_aquariids", name: "Delta Aquariids", start: "07-12", end: "08-23", peak: "07-30", radiant: "Aquarius", radiantAngle: 145, radiantAltitude: 34, color: "#0f766e" },
    { key: "perseids", name: "Perseids", start: "07-17", end: "08-24", peak: "08-12", radiant: "Perseus", radiantAngle: 45, radiantAltitude: 58, color: "#f59e0b" },
    { key: "draconids", name: "Draconids", start: "10-06", end: "10-10", peak: "10-08", radiant: "Draco", radiantAngle: 350, radiantAltitude: 66, color: "#65a30d" },
    { key: "orionids", name: "Orionids", start: "10-02", end: "11-07", peak: "10-21", radiant: "Orion", radiantAngle: 118, radiantAltitude: 48, color: "#db2777" },
    { key: "leonids", name: "Leonids", start: "11-06", end: "11-30", peak: "11-17", radiant: "Leo", radiantAngle: 95, radiantAltitude: 50, color: "#dc2626" },
    { key: "geminids", name: "Geminids", start: "12-04", end: "12-20", peak: "12-14", radiant: "Gemini", radiantAngle: 78, radiantAltitude: 64, color: "#9333ea" },
    { key: "ursids", name: "Ursids", start: "12-17", end: "12-26", peak: "12-22", radiant: "Ursa Minor", radiantAngle: 0, radiantAltitude: 72, color: "#0284c7" }
  ],
  constellations: [
    { month: 1, name: "Orion", highlight: { en: "Bright winter constellation with Betelgeuse, Rigel and the three Belt stars.", de: "Helles Wintersternbild mit Betelgeuse, Rigel und den drei Gürtelsternen.", fr: "Constellation hivernale brillante avec Bételgeuse, Rigel et les trois étoiles de la ceinture." }, stars: [[34,22],[48,36],[63,24],[45,50],[55,51],[36,76],[69,78]], lines: [[0,1],[1,2],[1,3],[3,4],[4,2],[3,5],[4,6]], labels: [{ star:0, name:"Betelgeuse", dx:-8, dy:-10, anchor:"end" }, { star:6, name:"Rigel", dx:8, dy:10 }, { star:3, name:"Mintaka", dx:-8, dy:0, anchor:"end" }] },
    { month: 2, name: "Gemini", highlight: { en: "Castor and Pollux form the twin heads high in the winter sky.", de: "Castor und Pollux bilden die Köpfe der Zwillinge hoch am Winterhimmel.", fr: "Castor et Pollux forment les têtes des Gémeaux haut dans le ciel d'hiver." }, stars: [[35,24],[62,28],[40,42],[65,45],[37,60],[69,64],[33,78],[72,82]], lines: [[0,2],[2,4],[4,6],[1,3],[3,5],[5,7],[2,3]], labels: [{ star:0, name:"Castor", dx:-8, dy:-10, anchor:"end" }, { star:1, name:"Pollux", dx:8, dy:-8 }] },
    { month: 3, name: "Leo", highlight: { en: "The Sickle marks Leo's head; Regulus anchors the spring constellation.", de: "Die Sichel markiert Leos Kopf; Regulus verankert das Frühlingssternbild.", fr: "La faucille marque la tête du Lion; Régulus ancre cette constellation de printemps." }, stars: [[25,62],[38,48],[44,30],[54,38],[59,57],[75,60],[86,50]], lines: [[0,1],[1,2],[2,3],[3,4],[4,5],[5,6]], labels: [{ star:0, name:"Regulus", dx:-8, dy:12, anchor:"end" }, { star:6, name:"Denebola", dx:8, dy:-4 }] },
    { month: 4, name: "Bootes", highlight: { en: "Arcturus is the orange beacon of spring and the base of the kite shape.", de: "Arktur ist der orangefarbene Frühlingsleuchtturm und die Basis der Drachenform.", fr: "Arcturus est le phare orangé du printemps et la base de la forme en cerf-volant." }, stars: [[50,20],[36,38],[62,40],[45,58],[56,60],[50,82]], lines: [[0,1],[0,2],[1,3],[2,4],[3,5],[4,5]], labels: [{ star:5, name:"Arcturus", dx:8, dy:12 }, { star:0, name:"Nekkar", dx:8, dy:-8 }] },
    { month: 5, name: "Virgo", highlight: { en: "Spica marks Virgo; the constellation stretches low and wide in spring.", de: "Spica markiert die Jungfrau; das Sternbild zieht sich im Frühling niedrig und breit über den Himmel.", fr: "Spica marque la Vierge; la constellation s'étire bas et largement au printemps." }, stars: [[18,45],[36,35],[52,48],[70,42],[82,62],[48,72]], lines: [[0,1],[1,2],[2,3],[3,4],[2,5]], labels: [{ star:5, name:"Spica", dx:8, dy:12 }, { star:2, name:"Porrima", dx:8, dy:-8 }] },
    { month: 6, name: "Hercules", highlight: { en: "A compact keystone shape between Vega and Arcturus.", de: "Eine kompakte Schlusssteinform zwischen Vega und Arktur.", fr: "Une forme compacte de clé de voûte entre Véga et Arcturus." }, stars: [[38,30],[61,28],[66,55],[42,58],[26,72],[75,75]], lines: [[0,1],[1,2],[2,3],[3,0],[3,4],[2,5]], labels: [{ star:0, name:"Pi Her", dx:-8, dy:-8, anchor:"end" }, { star:2, name:"Zeta Her", dx:8, dy:4 }] },
    { month: 7, name: "Scorpius", highlight: { en: "Antares glows red; from Europe the scorpion rides low in the south.", de: "Antares leuchtet rötlich; von Europa aus steht der Skorpion tief im Süden.", fr: "Antarès luit rouge; depuis l'Europe, le Scorpion reste bas au sud." }, stars: [[20,35],[36,42],[48,52],[58,60],[70,66],[82,58],[76,44],[62,36]], lines: [[0,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,7]], labels: [{ star:2, name:"Antares", dx:8, dy:-8 }, { star:5, name:"Shaula", dx:8, dy:6 }] },
    { month: 8, name: "Cygnus", highlight: { en: "The Northern Cross runs through the Milky Way with Deneb at the top.", de: "Das Nördliche Kreuz liegt in der Milchstraße, mit Deneb an der Spitze.", fr: "La Croix du Nord traverse la Voie lactée, avec Deneb à son sommet." }, stars: [[50,16],[50,36],[50,56],[50,80],[26,48],[74,48]], lines: [[0,1],[1,2],[2,3],[4,2],[2,5]], labels: [{ star:0, name:"Deneb", dx:8, dy:-8 }, { star:3, name:"Albireo", dx:8, dy:12 }, { star:4, name:"Gienah", dx:-8, dy:0, anchor:"end" }] },
    { month: 9, name: "Pegasus", highlight: { en: "The Great Square of Pegasus is a clear autumn landmark.", de: "Das Herbstviereck des Pegasus ist ein markanter Orientierungspunkt am Herbsthimmel.", fr: "Le Grand Carré de Pégase est un repère net du ciel d'automne." }, stars: [[28,30],[72,28],[75,70],[30,72],[88,46]], lines: [[0,1],[1,2],[2,3],[3,0],[1,4]], labels: [{ star:0, name:"Markab", dx:-8, dy:-8, anchor:"end" }, { star:1, name:"Alpheratz", dx:8, dy:-8 }, { star:4, name:"Enif", dx:8, dy:4 }] },
    { month: 10, name: "Andromeda", highlight: { en: "A chain of stars leading away from Pegasus toward the Andromeda Galaxy.", de: "Eine Sternenkette führt vom Pegasus weg in Richtung Andromedagalaxie.", fr: "Une chaîne d'étoiles part de Pégase vers la galaxie d'Andromède." }, stars: [[18,58],[36,48],[55,38],[72,31],[82,20],[62,56]], lines: [[0,1],[1,2],[2,3],[3,4],[2,5]], labels: [{ star:0, name:"Alpheratz", dx:-8, dy:10, anchor:"end" }, { star:2, name:"Mirach", dx:8, dy:-8 }, { star:4, name:"Almach", dx:8, dy:-8 }] },
    { month: 11, name: "Taurus", highlight: { en: "Aldebaran and the Hyades form the bull's face; the Pleiades sit nearby.", de: "Aldebaran und die Hyaden bilden das Gesicht des Stiers; die Plejaden stehen in der Nähe.", fr: "Aldébaran et les Hyades dessinent le visage du Taureau; les Pléiades sont toutes proches." }, stars: [[28,22],[40,30],[56,46],[42,56],[64,58],[76,36],[83,25]], lines: [[0,1],[1,2],[2,3],[2,4],[2,5],[5,6]], labels: [{ star:2, name:"Aldebaran", dx:8, dy:-8 }, { star:0, name:"Pleiades", dx:-8, dy:-8, anchor:"end" }, { star:6, name:"Elnath", dx:8, dy:-8 }] },
    { month: 12, name: "Auriga", highlight: { en: "Capella crowns the winter hexagon; Auriga is bright and compact.", de: "Capella krönt das Wintersechseck; der Fuhrmann ist hell und kompakt.", fr: "Capella couronne l'hexagone d'hiver; le Cocher est brillant et compact." }, stars: [[50,15],[28,36],[35,70],[67,72],[78,38]], lines: [[0,1],[1,2],[2,3],[3,4],[4,0]], labels: [{ star:0, name:"Capella", dx:8, dy:-8 }, { star:2, name:"Menkalinan", dx:-8, dy:12, anchor:"end" }] }
  ],
  spacecraft: [
    { key: "parker", name: "Parker Solar Probe", distanceAu: 0.16, angle: 250, region: "Inner heliosphere", color: "#f97316" },
    { key: "bepicolombo", name: "BepiColombo", distanceAu: 0.7, angle: 205, region: "Inner planets", color: "#eab308" },
    { key: "juice", name: "JUICE", distanceAu: 3.0, angle: 155, region: "To Jupiter", color: "#22c55e" },
    { key: "juno", name: "Juno", distanceAu: 5.2, angle: 115, region: "Jupiter", color: "#0ea5e9" },
    { key: "europa_clipper", name: "Europa Clipper", distanceAu: 5.2, angle: 82, region: "To Jupiter system", color: "#38bdf8" },
    { key: "new_horizons", name: "New Horizons", distanceAu: 60, angle: 34, region: "Kuiper belt", color: "#8b5cf6" },
    { key: "pioneer_10", name: "Pioneer 10", distanceAu: 137, angle: 356, region: "Outer heliosphere", color: "#64748b" },
    { key: "pioneer_11", name: "Pioneer 11", distanceAu: 113, angle: 304, region: "Outer heliosphere", color: "#94a3b8" },
    { key: "voyager_1", name: "Voyager 1", distanceAu: 165, angle: 18, region: "Interstellar space", color: "#ef4444" },
    { key: "voyager_2", name: "Voyager 2", distanceAu: 137, angle: 332, region: "Interstellar space", color: "#f43f5e" }
  ]
};
